"""add_ai_tables

Revision ID: 04ed8fce1de1
Revises: ce98582a7c79
Create Date: 2026-02-23 11:25:28.941083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04ed8fce1de1'
down_revision: Union[str, None] = 'ce98582a7c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('household_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_log_conversation_id'), 'ai_actions_log', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_log_household_id'), 'ai_actions_log', ['household_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('household_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_conv_type', 'ai_conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_ai_conversations_household_id'), 'ai_conversations', ['household_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_msg_created', 'ai_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('household_memory',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('household_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category', 'key', name='uq_household_memory_key')
    )
    op.create_index('idx_hm_active', 'household_memory', ['household_id', 'is_active'], unique=False)
    op.create_index('idx_hm_category', 'household_memory', ['household_id', 'category'], unique=False)
    op.create_index(op.f('ix_household_memory_household_id'), 'household_memory', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_memory_household_id'), table_name='household_memory')
    op.drop_index('idx_hm_category', table_name='household_memory')
    op.drop_index('idx_hm_active', table_name='household_memory')
    op.drop_table('household_memory')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index('idx_ai_msg_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_household_id'), table_name='ai_conversations')
    op.drop_index('idx_ai_conv_type', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_ai_actions_log_household_id'), table_name='ai_actions_log')
    op.drop_index(op.f('ix_ai_actions_log_conversation_id'), table_name='ai_actions_log')
    op.drop_table('ai_actions_log')
    # ### end Alembic commands ###
