"""add_chores_calendar_grocery_comments_magiclinks

Revision ID: ce98582a7c79
Revises: f870d6d7290c
Create Date: 2026-02-20 04:09:02.581531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce98582a7c79'
down_revision: Union[str, None] = 'f870d6d7290c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('household_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachments_household_id'), 'attachments', ['household_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('household_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_comments_household_id'), 'comments', ['household_id'], unique=False)
    op.create_table('magic_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('identifier_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_identifier'), 'magic_links', ['identifier'], unique=False)
    op.add_column('calendar_events', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('calendar_events', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('calendar_events', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('chores', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('chores', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('chores', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('chores', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('chores', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('grocery_lists', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('grocery_lists', 'delivery_date')
    op.drop_column('chores', 'location_lng')
    op.drop_column('chores', 'location_lat')
    op.drop_column('chores', 'location')
    op.drop_column('chores', 'due_date')
    op.drop_column('chores', 'status')
    op.drop_column('calendar_events', 'location_lng')
    op.drop_column('calendar_events', 'location_lat')
    op.drop_column('calendar_events', 'location')
    op.drop_index(op.f('ix_magic_links_identifier'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_comments_household_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_attachments_household_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
